### ISSUE TITLE
Actual Status

### ISSUE THREAD

**Issue by Mondonno** [knei-knurow/lidar-scan#14]
Can you provide the actual status of works on the lidar? I want to make some PR's but idk what work status you have, and I do not know what I can speed it up ;P

**Comment by bartekpacia** [comment]
we track tasks on our [Notion workspace](https://www.notion.so/a80ac8697ac44519a0cb414890f7ff18?v=b4f87d29dde0476faf19fa880a5656cc)
you can also ask questions on Mars#lidar discord channel

btw there's nothing interesting to do here now:P

**Comment by Mondonno** [comment]
Ok thanks!
