### ISSUE TITLE
bring back old behavior

### ISSUE THREAD

**Issue by bartekpacia** [knei-knurow/lidar-scan#17]
arguments for:
- we already have quite a few example clouds (and series) --> `datasets` folder (why waste time generating them again?)
- lidar-vis isn't compatible with it
- lidar-stream isn't compatible with it
- if we want to know the absolute time, we can just keep incrementing some `int sum`

**Comment by bartekpacia** [comment]
is it done @dsonyy?

**Comment by dsonyy** [comment]
> if we want to know the absolute time, we can just keep incrementing some int sum

This one is done, I've changed to the relative time.
> we already have quite a few example clouds (and series) --> datasets folder
> lidar-vis isn't compatible with it
> lidar-stream isn't compatible with it

Do you refer to _lidar-visualizations_ `dataset` directory? I don't understand exactly is wrong with those clouds,.

**Comment by bartekpacia** [comment]
> This one is done, I've changed to the relative time.

Thanks.

> Do you refer to lidar-visualizations dataset directory? I don't understand exactly is wrong with those clouds.

They use relative time. If we were to use absolute time in all of our tools (e.g `lidar-vis`), then those examples would not be compatible with them.

**Comment by dsonyy** [comment]
Oh, that's right. So it looks like everything is fine and the issue can be closed.
