### ISSUE TITLE
Investigate and fix why it doesn't work on odroid

### ISSUE THREAD

**Issue by bartekpacia** [knei-knurow/lidar-scan#21]
That's how it currently looks on out odroid (`dev/tty` is lidar and the connection is surely good, because it works well with my mac)
<img width="1439" alt="Screenshot 2021-01-10 at 14 02 38" src="https://user-images.githubusercontent.com/40357511/104123628-9c4f6180-534c-11eb-8eb7-3b80253dfdf9.png">

**Comment by bartekpacia** [comment]
@dsonyy @doodek any ideas on why this happens?

**Comment by doodek** [comment]
@bartekpacia 

It looks like the **newline sequence** issue. Are you sure a right CR+LF sequence is put to the terminal?

CR (carriage return) moves the cursor back to the beginning of the line, while LF (line feed) is responsible for moving to new line. Here, the cursor moves into new line, but does not go "back to the left", so I think that CR (carriage return) is not put to the tty.

**Comment by bartekpacia** [comment]
doesn't Unix-likes use only LF (`\n`)? CRLF seems like a Windows-only thing to me (`\r\n`)

+ this happens only on Arch on odroid, and works on macOS

**Comment by doodek** [comment]
@bartekpacia 
Now how about these strange characters at the beginning of some "lines"? Is it the same for other OS?

**Comment by bartekpacia** [comment]
only on Arch (but it was tested __only__ on Arch, so it's hard to tell)

**Comment by doodek** [comment]
Maybe try some other terminal emulator, like urxvt (rxvt-unicode), or xterm, if you use urxvt already

**Comment by doodek** [comment]
Or test it in before starting XFCE

**Comment by bartekpacia** [comment]
will try, thanks

**Comment by bartekpacia** [comment]
okay

it (unsurprisingly) turns out that I'm simply a dumb fuck and lidar isn't at `/dev/tty`, it's at `/dev/ttyUSB0`

also it needs sudo or just elevate permissions (`sudo chmod 777 /dev/ttyUSB0`)

I will add info about permissions to README
